function [Process_all,Noise_all,Process_avaiable,Noise_avaiable,Process_choosen,Noise_choosen]=Initialize_sets()
%u{1}=U
%u{2}=V
%u{3}=W
%u{4}=P
%u{5}=Q
%u{6}=R
%u{7}=X
%u{8}=Y
%u{9}=Z
%u{10}=L
%u{11}=M
%u{12}=N
%     @(t,u,y)u{2}(t-1)*u{4}(t-1) ...
%     @(t,u,y)u{2}(t-1)*u{5}(t-1) ...
%     @(t,u,y)u{8}(t-1) ...
%     @(t,u,y)u{9}(t-1) ...
Process_all={@(t,u,y)y(t-1) ...
    @(t,u,y)u{2}(t-1)*u{6}(t-1) ...
    @(t,u,y)u{3}(t-1)*u{5}(t-1) ...
    @(t,u,y)u{3}(t-1)*u{6}(t-1) ...
    @(t,u,y)u{3}(t-1)*u{4}(t-1) ...
    @(t,u,y)u{7}(t-1) ...
    @(t,u,y)y(t-1)^2 ...
       };
   
Noise_all={%@(t,u,y,e)e(t-1)...
            @(t,u,y,e)e(t-1)*u{2}(t-1)...
            @(t,u,y,e)e(t-1)*u{3}(t-1)...
            @(t,u,y,e)e(t-1)*u{4}(t-1)};


Process_avaiable=1:length(Process_all);
Process_choosen=[];

     
Noise_avaiable=1:length(Noise_all);
Noise_choosen=[];
end